# Generated by Django 6.0.6 on 2026-06-10 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_savedproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Commercial', 'Commercial'), ('Penthouse', 'Penthouse'), ('Plot', 'Plot')], max_length=50)),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=50)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=1)),
                ('sqft', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
